"""Original background beats for Reels, synthesized from scratch.

Every track is generated by this code (no samples, no loops, no third-party audio),
so there are no licensing or copyright claims on it. Each Reel gets a variation
(key, tempo, melody) seeded from its post key.
"""
import math
import random
import struct
import wave

RATE = 22050
PROGRESSIONS = [  # minor-key loops (semitones from the key root): i-VI-III-VII, i-iv-VI-V, i-VII-VI-VII
    [(0, 3, 7), (-4, 0, 3), (3, 7, 10), (-2, 2, 5)],
    [(0, 3, 7), (5, 8, 12), (-4, 0, 3), (-5, -1, 2)],
    [(0, 3, 7), (-2, 2, 5), (-4, 0, 3), (-2, 2, 5)],
]
KEYS = [57, 55, 52, 53, 50]  # MIDI roots: A, G, E, F, D


def _hz(midi):
    return 440.0 * 2 ** ((midi - 69) / 12)


def make_beat(path, seconds, seed="sharpcharts"):
    rnd = random.Random(seed)
    bpm = rnd.choice([88, 92, 96, 100])
    key = rnd.choice(KEYS)
    prog = rnd.choice(PROGRESSIONS)
    beat = 60.0 / bpm
    n = int(seconds * RATE)
    buf = [0.0] * n

    def add(start_s, dur_s, fn):
        s0 = int(start_s * RATE)
        for i in range(max(0, s0), min(n, s0 + int(dur_s * RATE))):
            buf[i] += fn((i - s0) / RATE)

    noise = [rnd.uniform(-1, 1) for _ in range(RATE)]
    beats = int(seconds / beat) + 1
    for b in range(beats):
        t0 = b * beat
        chord = prog[(b // 4) % len(prog)]
        root = key + chord[0] - 24
        # drums
        if b % 4 in (0, 2):
            add(t0, 0.35, lambda t: 0.9 * math.sin(2 * math.pi * (45 * t + 105 / 30 * (1 - math.exp(-30 * t)))) * math.exp(-9 * t))
        if b % 4 == 2 and rnd.random() < 0.5:
            add(t0 + beat / 2, 0.3, lambda t: 0.6 * math.sin(2 * math.pi * (45 * t + 105 / 30 * (1 - math.exp(-30 * t)))) * math.exp(-10 * t))
        if b % 2 == 1:
            add(t0, 0.2, lambda t: 0.35 * (noise[int(t * RATE)] - noise[int(t * RATE) - 1]) * math.exp(-22 * t))
        for h in (0, 0.5):
            add(t0 + h * beat, 0.06, lambda t: 0.09 * (noise[int(t * RATE) + 500] - noise[int(t * RATE) + 499]) * math.exp(-70 * t))
        # bass
        f = _hz(root)
        add(t0, beat * 0.9, lambda t, f=f: 0.32 * math.sin(2 * math.pi * f * t) * min(1, t * 60) * math.exp(-2.2 * t))
        # pad (soft triangle chord), once per bar
        if b % 4 == 0:
            for semi in chord:
                fp = _hz(key + semi)
                add(t0, beat * 4, lambda t, fp=fp: 0.045 * (2 / math.pi) * math.asin(math.sin(2 * math.pi * fp * t))
                    * min(1, t * 4) * min(1, (beat * 4 - t) * 4))
        # pluck arpeggio on 8ths
        for h in (0, 0.5):
            semi = chord[rnd.randrange(3)] + 12
            fm = _hz(key + semi)
            add(t0 + h * beat, 0.4, lambda t, fm=fm: 0.11 * math.sin(2 * math.pi * fm * t) * math.exp(-9 * t))

    fade_in, fade_out = int(0.1 * RATE), int(1.0 * RATE)
    frames = bytearray()
    for i, x in enumerate(buf):
        g = min(1.0, i / fade_in, (n - i) / fade_out)
        y = math.tanh(1.2 * x) * 0.8 * g
        frames += struct.pack("<h", int(y * 32767))
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(bytes(frames))
    return {"bpm": bpm, "key": key}
